### PR TITLE
misc: support for esdb 21.10.x

### PR DESCRIPTION
**Pull request by ahjohannessen**
- add support for node state `DiscoverLeader` and `ResigningLeader`.

 - adjust tests for soft delete scenarios that
   are not supported in esdb 21.10.0.

 - upgrade various dependencies.

 - adjust travis file for esdb updates

 - fix compiler warning about deprecated usage
   wrt. since not being stable identifier.

 NOTE: all tests have been run locally as travis is no more.

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@t3hnar Are you still able to merge and publish? :) I have another PR on EventStore.Akka.Persistence that relies on this one being merged.

**Comment by t3hnar** [comment]
@ahjohannessen I hope so, please let me know when you're finished with this one :)

**Comment by t3hnar** [comment]
> NOTE: all tests have been run locally as travis is no more.

did you consider switching to GitHub actions?

**Comment by ahjohannessen** [comment]
@t3hnar I just merged CI actions into this branch for GH

**Comment by ahjohannessen** [comment]
@t3hnar I'll do that same with the Akka.Persistence PR wrt. CI

**Comment by ahjohannessen** [comment]
It requires a release of this to run

**Comment by t3hnar** [comment]
released under `v7.4.0`

**Comment by ahjohannessen** [comment]
👍 Updated the Akka.Persistence PR to reflect that.

**Pull request merged**
