### PR TITLE
all: Scala 3 support

### PR DESCRIPTION
**Pull request by ahjohannessen**
- replace akka-http / akka-http-spray and spray-json with
   sttp / okhttp / circe in order to move to Scala 3.

 - adjust code to new http transport.

 - remove `HttpSettings` from client as it contains
   akka-http `Uri`.

 - remove deprecated code.

 - upgrade all dependencies to latest stable version.

 - change CI to use Scala 3.1.0 for integration / cluster
   tests and bump eventstore docker image.

 - remove travis CI definition.

 - adjust build file for sbt. 1.5.8

Note: This is a breaking change & major version increase is needed

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@t3hnar It is me again 🕺 Now with Scala 3 - As akka-http is not even there yet and akka supports Scala 3 as of 2.6.18, I ripped akka-http / akka-http-spray / spray-json out and replaced that with sttp / okhttp / circe as we get to Scala 3 with those.

This needs a 8.0.0 version as `HttpSettings` is removed.

WDYT?

**Comment by ahjohannessen** [comment]
@t3hnar I have another [PR](https://github.com/ahjohannessen/EventStore.JVM/pull/5/files) waiting. That PR adds support for sbt-gh-actions and sbt-ci-release such that releases can be made with tags and github actions are generated from sbt. 

However, this PR is more important to get in and released, so I'll open that one as soon this one gets merged.

**Comment by t3hnar** [comment]
`v8.0.0` it is

**Comment by ahjohannessen** [comment]
👍

**Pull request merged**
