### PR TITLE
build: bump dependencies

### PR DESCRIPTION
**Pull request by ahjohannessen**
- bump various dependencies
 - bump scala 2.12

### CODE REVIEW

**Comment by t3hnar** [comment]
@ahjohannessen Unfortunately I don't have rights to merge pull requests, I hope this is a temporary issue.

**Comment by ahjohannessen** [comment]
@gregoryyoung Any chance you can give @t3hnar rights?

**Comment by riccardone** [comment]
@t3hnar I've just sent an invitation

**Comment by t3hnar** [comment]
@riccardone thx

**Pull request merged**
