### PR TITLE
akka: replace subscription actors with adapter

### PR DESCRIPTION
**Pull request by ahjohannessen**
- change `SourceStageLogic` to fail stage if
   upstream completes, because we expect the
   connection to have a long lifespan and never
   complete.

 - replace `SubscriptionActor` & `StreamSubscriptonActor`
   with `StreamAdapter` that provides similar behavior and
   delete related code that is not needed anymore.

 - adjust `StreamSubscriptActorSpec` & `SubscriptinActorSpec`
   to showcase that we maintain same behavior. These specs
   are subject for future removal.

 - add live callback to `StreamSourceLogic` in order
   to have similar behavior wrt. `LiveProcessingStarted`
   in `StreamAdapter`.

 - remove unecessary `AbstractPersistentSubscriptionActor`
   as it is not bringing about any advantage, plus that
   `PersistentSubscriptionActor` is subject for a stream
   based replacement in the future.

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@t3hnar This PR should not be merged, as I think we should rather deprecate all usage of `SubscriptionActor`, `StreamSubscriptonActor`, `SubscriptionObserver` and `SubscriptionObserver` and point people to use streams, thus no need for an adapter. 

Usage of `LiveProcessingStarted` is not needed when using streams - The only usage of it is to determine if one should end the subsription observer, i.e. the reason for the `Closeable` parameter. You can accomplish all of this by using our streams alone, e.g. use `infinite` as a way to shut down when end of stream is reached or just keep going.

If there are people that insist on using `SubscriptionObserver` and `LiveProcessingStarted` we could take this code and put in a new `eventstore-client-legacy` project.

**Comment by t3hnar** [comment]
@ahjohannessen should I just close it and reopen later ?

**Comment by ahjohannessen** [comment]
@t3hnar sure, I'll that

**Comment by ahjohannessen** [comment]
@t3hnar I mostly wanted to spark a conversation about moving away from actors where we have replacements that are based on streams.

**Pull request closed without merging**
