### PR TITLE
all: scala 2.13.0

### PR DESCRIPTION
**Pull request by ahjohannessen**
- adjust code according to changes from Scala version
   2.13.0-M5 to 2.13.0.

 - bump dependencies:
   - akka:2.5.23
   - scodec-bits:1.1.12
   - typesafe-config:1.3.4

 - make 2.13.0 default for build.sbt and travis

 - bump sbt plugins:
   - tpolecat-plugin: 0.1.6
   - sbt-scoverage: 1.6.0

 - adjust README to changes in example code.

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@t3hnar WDYT?

**Comment by t3hnar** [comment]
> @t3hnar WDYT?

I though you lost the interest :D

**Comment by ahjohannessen** [comment]
No :) Busy at work. Got another PR that is based on this with a changelog file. 3 mins

**Comment by ahjohannessen** [comment]
Change log here #144 :)

**Comment by ahjohannessen** [comment]
Travis is green @t3hnar :)

**Comment by ahjohannessen** [comment]
Updated the PR as I realized that I could do this for `ScalaCompat` for 2.12:
```scala
val JavaConverters = scala.collection.JavaConverters
```
and for 2.13
```scala
val JavaConverters = scala.jdk.CollectionConverters
```
:)

**Comment by ahjohannessen** [comment]
Thanks @t3hnar :) Could you please publish v7.0.0 for 2.12.8 and 2.13.0?

**Comment by t3hnar** [comment]
@ahjohannessen no more breaking changes expected ?

**Comment by ahjohannessen** [comment]
@t3hnar Not as far as I can tell.

**Comment by t3hnar** [comment]
@ahjohannessen done, might take some time before available globally

**Comment by ahjohannessen** [comment]
@t3hnar Thanks, will update this https://github.com/EventStore/EventStore.Akka.Persistence/pull/47 once libs are available.

**Comment by ahjohannessen** [comment]
@t3hnar is v7.0.0 you published compiled with jdk11? I get the following:

>Java.lang.UnsupportedClassVersionError: eventstore/proto/EventStoreMessages$WriteEvents has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I am on jdk8

**Comment by t3hnar** [comment]
hm, let me check, I though sbt explicitly set java compile mode to `1.8` ...

**Comment by ahjohannessen** [comment]
@t3hnar I think the most robust approach to ensure jdk class file format is to specify this in the build:

```scala
ThisBuild / scalacOptions ++= Seq("-target:jvm-1.8")
ThisBuild / javacOptions ++= Seq("-target", "8", "-source", "8")
```

**Comment by t3hnar** [comment]
@ahjohannessen please create PR, I'm releasing `7.0.1` meanwhile :D

**Comment by ahjohannessen** [comment]
I have :)

**Pull request merged**
